# https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure

name: Az CLI Login using OIDC

on:
  workflow_dispatch:
  workflow_call:
#     secrets:
#       AZURE_TENANT_ID:
#         required: true
#       AZURE_CLIENT_ID:
#         required: true
#       AZURE_SUBSCRIPTION_ID:
#         required: true

permissions:
  id-token: write
  contents: read

jobs:
  az-login:
    runs-on: ubuntu-latest
    environment: azure
    steps:
      - name: Az CLI Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
