name: Az CLI Logout using OIDC

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  az-logout:
    runs-on: ubuntu-latest
    environment: azure
    steps:
      - name: Az CLI Logout
        run: az logout
