# https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity#add-a-user-assigned-identity

name: Create Azure User Assigned Managed Identity

on:
  workflow_dispatch:
    inputs:
      group:
        description: Resource group name
        type: text
        default: mygroup
        required: true
      name:
        description: Resource name
        type: text
        default: myidentity
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  create-resource:
    runs-on: ubuntu-latest
    environment: azure
    steps:
      - name: Az CLI Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create identity
        run: az identity create --resource-group ${{ inputs.group }} --name ${{ inputs.name }}
      - name: Az CLI Logout
        run: az logout
